export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAILURE = "CREATE_CONTACT_FAILURE";

export const CREATE_VEHICLES_REQUEST = "CREATE_VEHICLES_REQUEST";
export const CREATE_VEHICLES_SUCCESS = "CREATE_VEHICLES_SUCCESS";
export const CREATE_VEHICLES_FAILURE = "CREATE_VEHICLES_FAILURE";

export const NEXT_PAGE = "NEXT_PAGE";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";